-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MASH_HDL\MATLAB_Function.vhd
-- Created: 2018-01-07 05:13:35
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: MASH_HDL/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MATLAB_Function IS
  PORT( quant_in                          :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En25
        nLev                              :   IN    real;  -- double
        quant_out                         :   OUT   std_logic_vector(35 DOWNTO 0)  -- sfix36_En25
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Signals
  SIGNAL quant_in_signed                  : signed(35 DOWNTO 0);  -- sfix36_En25
  SIGNAL quant_out_tmp                    : signed(35 DOWNTO 0);  -- sfix36_En25

BEGIN
  quant_in_signed <= signed(quant_in);

  -- st=fi(nLev-2,1,34,22);
  -- quant_out=fi(0,1,34,22);
  -- if quant_in < -st
  --     quant_out = fi(-nLev+1,1,34,22);
  --     %     return;
  -- elseif quant_in >= st
  --     quant_out = fi(nLev-1,1,34,22);
  --     %     return;
  -- else
  --     for n=1:nLev-2
  --         k=fi(n,1,34,22);
  --         if quant_in >= -nLev + 2*k && quant_in < -nLev + 2*(k+1)
  --             quant_out = fi(2*k-1-nLev,1,34,22);
  --         end
  --     end
  -- end
  --y = -1;
  --y = 1;
  
  quant_out_tmp <= to_signed(-33554432, 36) WHEN quant_in_signed < to_signed(0, 36) ELSE
      to_signed(33554432, 36);

  quant_out <= std_logic_vector(quant_out_tmp);

END rtl;

