% -------------------------------------------------------------------
%  Generated by MATLAB on 6-Jan-2018 23:58:53
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
saveVarsMat = load('LTE_waveform.mat');

tx = saveVarsMat.tx; % <1x1 struct> too many elements at tx.signals.values

clear saveVarsMat;
