# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Newcomputer/DSM_Final/DSM_Final/project_1/project_1.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Newcomputer/DSM_Final/DSM_Final/ipcore_dir/coregen.cgc"

set ipFile "c:/Newcomputer/DSM_Final/DSM_Final/ipcore_dir/Clock_Generator_1.xco"

set ipName "Clock_Generator_1"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "c:/Newcomputer/DSM_Final/DSM_Final/ipcore_dir/pa_cg_bom.xml"

set cgPartSpec "xc6slx150-3fgg484"

set hdlType "VHDL"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

