# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Newcomputer/DSM_Final/DSM_Final/project_1/project_1.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Newcomputer/DSM_Final/DSM_Final/project_1/project_1.srcs/sources_1/ip/dds_compiler_v4_0_0/coregen.cgc"

set ipFile "c:/Newcomputer/DSM_Final/DSM_Final/project_1/project_1.srcs/sources_1/ip/dds_compiler_v4_0_0/dds_compiler_v4_0_0.xco"

set ipName "dds_compiler_v4_0_0"

set hdlType "VHDL"

set cgPartSpec "xc7z045-3ffg900"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "c:/Newcomputer/DSM_Final/DSM_Final/project_1/project_1.srcs/sources_1/ip/dds_compiler_v4_0_0/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

