-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\DSM_MOD8_HDL\Quantizer.vhd
-- Created: 2018-01-07 17:03:01
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Quantizer
-- Source Path: DSM_MOD8_HDL/Quantizer
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Quantizer IS
  PORT( u                                 :   IN    std_logic_vector(45 DOWNTO 0);  -- sfix46_En40
        y                                 :   OUT   std_logic_vector(45 DOWNTO 0)  -- sfix46_En40
        );
END Quantizer;


ARCHITECTURE rtl OF Quantizer IS

  -- Signals
  SIGNAL u_signed                         : signed(45 DOWNTO 0);  -- sfix46_En40
  SIGNAL y_tmp                            : signed(45 DOWNTO 0);  -- sfix46_En40

BEGIN
  u_signed <= signed(u);

  
  y_tmp <= signed'("1111110000000000000000000000000000000000000000") WHEN u_signed < to_signed(0, 46) ELSE
      signed'("0000010000000000000000000000000000000000000000");

  y <= std_logic_vector(y_tmp);

END rtl;

