-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\DSM_MOD8_HDL\Sign.vhd
-- Created: 2018-01-07 17:03:01
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Sign
-- Source Path: DSM_MOD8_HDL/Sign
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Sign IS
  PORT( u                                 :   IN    std_logic_vector(45 DOWNTO 0);  -- sfix46_En40
        y                                 :   OUT   std_logic_vector(1 DOWNTO 0)  -- sfix2
        );
END Sign;


ARCHITECTURE rtl OF Sign IS

  -- Signals
  SIGNAL u_signed                         : signed(45 DOWNTO 0);  -- sfix46_En40
  SIGNAL y_tmp                            : signed(1 DOWNTO 0);  -- sfix2

BEGIN
  u_signed <= signed(u);

  
  y_tmp <= to_signed(2#11#, 2) WHEN u_signed < to_signed(0, 46) ELSE
      to_signed(2#01#, 2);

  y <= std_logic_vector(y_tmp);

END rtl;

