-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\turnkey_test_model\DUT_topatlys.vhd
-- Created: 2017-12-29 18:33:14
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DUT_topatlys
-- Source Path: DUT_topatlys
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DUT_topatlys IS
  PORT( CLKIN                             :   IN    std_logic;  -- ufix1
        RESETIN_n                         :   IN    std_logic;  -- ufix1
        LEDs                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
        );
END DUT_topatlys;


ARCHITECTURE rtl OF DUT_topatlys IS

  -- Component Declarations
  COMPONENT DUT_topatlys_clock_module
    PORT( clkin                           :   IN    std_logic;  -- ufix1
          resetin                         :   IN    std_logic;  -- ufix1
          sysclk                          :   OUT   std_logic;
          sysreset                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT DUT
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          ce_out                          :   OUT   std_logic;  -- ufix1
          Out1                            :   OUT   std_logic_vector(7 DOWNTO 0)  -- ufix8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : DUT_topatlys_clock_module
    USE ENTITY work.DUT_topatlys_clock_module(rtl);

  FOR ALL : DUT
    USE ENTITY work.DUT(rtl);

  -- Signals
  SIGNAL clk                              : std_logic;
  SIGNAL reset                            : std_logic;
  SIGNAL enb                              : std_logic;
  SIGNAL const_1                          : std_logic;  -- ufix1
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL Out1_sig                         : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_DUT_topatlys_clock_module_inst : DUT_topatlys_clock_module
    PORT MAP( clkin => CLKIN,  -- ufix1
              resetin => reset_cm,  -- ufix1
              sysclk => clk,
              sysreset => reset
              );

  u_DUT : DUT
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              ce_out => ce_out_sig,  -- ufix1
              Out1 => Out1_sig  -- ufix8
              );

  const_1 <= '1';

  enb <= const_1;

  reset_cm <=  NOT RESETIN_n;

  LEDs <= Out1_sig;

END rtl;

