-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\turnkey_test_model\DUT_topatlys_clock_module.vhd
-- Created: 2017-12-29 18:33:14
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DUT_topatlys_clock_module
-- Source Path: DUT_topatlys/DUT_topatlys_clock_module
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
LIBRARY UNISIM;
USE UNISIM.vcomponents.ALL;

ENTITY DUT_topatlys_clock_module IS
  PORT( clkin                             :   IN    std_logic;  -- ufix1
        resetin                           :   IN    std_logic;  -- ufix1
        sysclk                            :   OUT   std_logic;  -- ufix1
        sysreset                          :   OUT   std_logic  -- ufix1
        );
END DUT_topatlys_clock_module;


ARCHITECTURE rtl OF DUT_topatlys_clock_module IS

  -- Component Declarations
  COMPONENT IBUFG
    PORT( I                               :   IN    std_logic;  -- ufix1
          O                               :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT DCM_SP
    PORT( CLKIN                           :   IN    std_logic;  -- ufix1
          CLKFB                           :   IN    std_logic;  -- ufix1
          RST                             :   IN    std_logic;  -- ufix1
          PSEN                            :   IN    std_logic;  -- ufix1
          CLK0                            :   OUT   std_logic;  -- ufix1
          LOCKED                          :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT BUFG
    PORT( I                               :   IN    std_logic;  -- ufix1
          O                               :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Signals
  SIGNAL ibufg_out                        : std_logic;  -- ufix1
  SIGNAL const_0                          : std_logic;  -- ufix1
  SIGNAL sysclk_1                         : std_logic;  -- ufix1
  SIGNAL dcm_out                          : std_logic;  -- ufix1
  SIGNAL locked                           : std_logic;  -- ufix1

BEGIN
  u_IBUFG : IBUFG
    PORT MAP( I => clkin,  -- ufix1
              O => ibufg_out  -- ufix1
              );

  u_DCM_SP : DCM_SP
    PORT MAP( CLKIN => ibufg_out,  -- ufix1
              CLKFB => sysclk_1,  -- ufix1
              RST => resetin,  -- ufix1
              PSEN => const_0,  -- ufix1
              CLK0 => dcm_out,  -- ufix1
              LOCKED => locked  -- ufix1
              );

  u_BUFG : BUFG
    PORT MAP( I => dcm_out,  -- ufix1
              O => sysclk_1  -- ufix1
              );

  const_0 <= '0';

  sysreset <=  NOT locked;

  sysclk <= sysclk_1;

END rtl;

