######################################################################
##
## Filename: all_digital_modulator.udo
## Created on: Mon Jan 08 4:25:12 AM Eastern Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
