-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\dsm_mod8_fpga\Eight_order_delta_sigma_modulator.vhd
-- Created: 2017-12-27 18:44:57
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Modulator_output              ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Eight_order_delta_sigma_modulator
-- Source Path: dsm_mod8_fpga/Eight_order_delta_sigma_modulator
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Eight_order_delta_sigma_modulator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Baseband_signal                   :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En32
        ce_out                            :   OUT   std_logic;
        Modulator_output                  :   OUT   std_logic_vector(35 DOWNTO 0)  -- sfix36_En32
        );
END Eight_order_delta_sigma_modulator;


ARCHITECTURE rtl OF Eight_order_delta_sigma_modulator IS

  -- Component Declarations
  COMPONENT MATLAB_Function
    PORT( u                               :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En32
          y                               :   OUT   std_logic_vector(35 DOWNTO 0)  -- sfix36_En32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MATLAB_Function
    USE ENTITY work.MATLAB_Function(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Baseband_signal_signed           : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain24_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain28_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain18_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain15_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain8_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain7_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain6_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain5_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain_mul_temp                    : signed(71 DOWNTO 0);  -- sfix72_En64
  SIGNAL Gain_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL y_signed                         : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain25_mul_temp                  : signed(71 DOWNTO 0);  -- sfix72_En67
  SIGNAL Gain25_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum15_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Delay6_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain23_mul_temp                  : signed(71 DOWNTO 0);  -- sfix72_En69
  SIGNAL Gain23_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain19_mul_temp                  : signed(71 DOWNTO 0);  -- sfix72_En71
  SIGNAL Gain19_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum9_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Delay4_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain17_mul_temp                  : signed(71 DOWNTO 0);  -- sfix72_En74
  SIGNAL Gain17_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain4_mul_temp                   : signed(71 DOWNTO 0);  -- sfix72_En76
  SIGNAL Gain4_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum5_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Delay2_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain3_mul_temp                   : signed(71 DOWNTO 0);  -- sfix72_En81
  SIGNAL Gain3_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain2_mul_temp                   : signed(71 DOWNTO 0);  -- sfix72_En83
  SIGNAL Gain2_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum1_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Delay_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL y                                : std_logic_vector(35 DOWNTO 0);  -- ufix36
  SIGNAL Gain1_mul_temp                   : signed(71 DOWNTO 0);  -- sfix72_En89
  SIGNAL Gain1_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Delay1_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain9_mul_temp                   : signed(71 DOWNTO 0);  -- sfix72_En64
  SIGNAL Gain9_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum_op_stage2                    : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Modulator_input                  : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum1_add_temp                    : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum2_op_stage2                   : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum2_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum3_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Delay3_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain10_mul_temp                  : signed(71 DOWNTO 0);  -- sfix72_En64
  SIGNAL Gain10_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum4_op_stage2                   : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum4_op_stage3                   : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum4_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum6_op_stage2                   : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum6_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum7_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Delay5_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain20_mul_temp                  : signed(71 DOWNTO 0);  -- sfix72_En64
  SIGNAL Gain20_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum8_op_stage2                   : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum8_op_stage3                   : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum8_out1                        : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum10_op_stage2                  : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum10_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum11_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Delay7_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Gain26_mul_temp                  : signed(71 DOWNTO 0);  -- sfix72_En64
  SIGNAL Gain26_out1                      : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum14_op_stage2                  : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum14_op_stage3                  : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum14_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum12_op_stage2                  : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum12_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL Sum13_out1                       : signed(35 DOWNTO 0);  -- sfix36_En32

BEGIN
  u_MATLAB_Function : MATLAB_Function
    PORT MAP( u => std_logic_vector(Delay7_out1),  -- sfix36_En32
              y => y  -- sfix36_En32
              );

  Baseband_signal_signed <= signed(Baseband_signal);

  Gain24_out1 <= to_signed(0, 36);

  Gain28_out1 <= to_signed(0, 36);

  Gain18_out1 <= to_signed(0, 36);

  Gain15_out1 <= to_signed(0, 36);

  Gain8_out1 <= to_signed(0, 36);

  Gain7_out1 <= to_signed(0, 36);

  Gain6_out1 <= to_signed(0, 36);

  Gain5_out1 <= to_signed(0, 36);

  Gain_mul_temp <= to_signed(642, 36) * Baseband_signal_signed;
  Gain_out1 <= Gain_mul_temp(67 DOWNTO 32);

  enb <= clk_enable;

  Gain25_mul_temp <= signed'(X"491FC4622") * y_signed;
  Gain25_out1 <= Gain25_mul_temp(70 DOWNTO 35);

  Delay6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay6_out1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay6_out1 <= Sum15_out1;
      END IF;
    END IF;
  END PROCESS Delay6_process;


  Gain23_mul_temp <= signed'(X"67B091812") * y_signed;
  Gain23_out1 <= resize(Gain23_mul_temp(71 DOWNTO 37), 36);

  Gain19_mul_temp <= signed'(X"5BBD4B283") * y_signed;
  Gain19_out1 <= resize(Gain19_mul_temp(71 DOWNTO 39), 36);

  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_out1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_out1 <= Sum9_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  Gain17_mul_temp <= signed'(X"4BF3D56B3") * y_signed;
  Gain17_out1 <= resize(Gain17_mul_temp(71 DOWNTO 42), 36);

  Gain4_mul_temp <= signed'(X"45E224032") * y_signed;
  Gain4_out1 <= resize(Gain4_mul_temp(71 DOWNTO 44), 36);

  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Sum5_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  Gain3_mul_temp <= signed'(X"6F7E38958") * y_signed;
  Gain3_out1 <= resize(Gain3_mul_temp(71 DOWNTO 49), 36);

  Gain2_mul_temp <= signed'(X"4C532F286") * y_signed;
  Gain2_out1 <= resize(Gain2_mul_temp(71 DOWNTO 51), 36);

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay_out1 <= Sum1_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  y_signed <= signed(y);

  Gain1_mul_temp <= signed'(X"50451A854") * y_signed;
  Gain1_out1 <= resize(Gain1_mul_temp(71 DOWNTO 57), 36);

  Gain9_mul_temp <= to_signed(5571177, 36) * Delay1_out1;
  Gain9_out1 <= Gain9_mul_temp(67 DOWNTO 32);

  Sum_op_stage2 <= Gain_out1 - Gain9_out1;

  Modulator_input <= Sum_op_stage2 - Gain1_out1;

  Sum1_add_temp <= Gain5_out1 + Modulator_input;
  Sum1_out1 <= Sum1_add_temp + Delay_out1;

  Sum2_op_stage2 <= Gain6_out1 + Sum1_out1;

  Sum2_out1 <= Sum2_op_stage2 - Gain2_out1;

  Sum3_out1 <= Sum2_out1 + Delay1_out1;

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= Sum3_out1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Gain10_mul_temp <= to_signed(45691454, 36) * Delay3_out1;
  Gain10_out1 <= Gain10_mul_temp(67 DOWNTO 32);

  Sum4_op_stage2 <= Gain7_out1 - Gain10_out1;

  Sum4_op_stage3 <= Sum4_op_stage2 + Delay1_out1;

  Sum4_out1 <= Sum4_op_stage3 - Gain3_out1;

  Sum5_out1 <= Sum4_out1 + Delay2_out1;

  Sum6_op_stage2 <= Gain8_out1 + Sum5_out1;

  Sum6_out1 <= Sum6_op_stage2 - Gain4_out1;

  Sum7_out1 <= Sum6_out1 + Delay3_out1;

  Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay3_out1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay3_out1 <= Sum7_out1;
      END IF;
    END IF;
  END PROCESS Delay3_process;


  Gain20_mul_temp <= to_signed(104878722, 36) * Delay5_out1;
  Gain20_out1 <= Gain20_mul_temp(67 DOWNTO 32);

  Sum8_op_stage2 <= Gain15_out1 - Gain20_out1;

  Sum8_op_stage3 <= Sum8_op_stage2 + Delay3_out1;

  Sum8_out1 <= Sum8_op_stage3 - Gain17_out1;

  Sum9_out1 <= Sum8_out1 + Delay4_out1;

  Sum10_op_stage2 <= Gain18_out1 + Sum9_out1;

  Sum10_out1 <= Sum10_op_stage2 - Gain19_out1;

  Sum11_out1 <= Sum10_out1 + Delay5_out1;

  Delay5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay5_out1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay5_out1 <= Sum11_out1;
      END IF;
    END IF;
  END PROCESS Delay5_process;


  Gain26_mul_temp <= to_signed(152243002, 36) * Delay7_out1;
  Gain26_out1 <= Gain26_mul_temp(67 DOWNTO 32);

  Sum14_op_stage2 <= Gain28_out1 - Gain26_out1;

  Sum14_op_stage3 <= Sum14_op_stage2 + Delay5_out1;

  Sum14_out1 <= Sum14_op_stage3 - Gain23_out1;

  Sum15_out1 <= Sum14_out1 + Delay6_out1;

  Sum12_op_stage2 <= Gain24_out1 + Sum15_out1;

  Sum12_out1 <= Sum12_op_stage2 - Gain25_out1;

  Sum13_out1 <= Sum12_out1 + Delay7_out1;

  Delay7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay7_out1 <= to_signed(0, 36);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay7_out1 <= Sum13_out1;
      END IF;
    END IF;
  END PROCESS Delay7_process;


  ce_out <= clk_enable;

  Modulator_output <= y;

END rtl;

