-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\DSM_MOD4_HDL\Fourth_order_delta_sigma_modulator_pkg.vhd
-- Created: 2018-01-08 05:39:59
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Fourth_order_delta_sigma_modulator_pkg IS
  TYPE vector_of_signed36 IS ARRAY (NATURAL RANGE <>) OF signed(35 DOWNTO 0);
END Fourth_order_delta_sigma_modulator_pkg;

