tclcmd = { ...
'vsimulink all_digital_modulator -t 1ps -voptargs=+acc  -socket 51181;', ...
'add wave all_digital_modulator/*;', ...
};
vsim('tclstart',tclcmd,'vsimdir','C:\Modeltech_pe_edu_10.4a\win32pe_edu')
