-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\dsm_fpga_mod4\MATLAB_Function.vhd
-- Created: 2017-12-27 18:43:17
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: dsm_fpga_mod4/Fourth_order_delta_sigma_modulator/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MATLAB_Function IS
  PORT( u                                 :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En32
        y                                 :   OUT   std_logic_vector(35 DOWNTO 0)  -- sfix36_En32
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Signals
  SIGNAL u_signed                         : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL y_tmp                            : signed(35 DOWNTO 0);  -- sfix36_En32

BEGIN
  u_signed <= signed(u);
  
  y_tmp <= signed'(X"F00000000") WHEN u_signed < to_signed(0, 36) ELSE
      signed'(X"100000000");

  y <= std_logic_vector(y_tmp);

END rtl;

