--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.7
--  \   \         Application : xaw2vhdl
--  /   /         Filename : PLL_CLOCK.vhd
-- /___/   /\     Timestamp : 01/08/2018 04:20:50
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st C:\Newcomputer\DSM_Final\DSM_Final\.\PLL_CLOCK.xaw C:\Newcomputer\DSM_Final\DSM_Final\.\PLL_CLOCK
--Design Name: PLL_CLOCK
--Device: xc5vlx20t-2ff323
--
-- Module PLL_CLOCK
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT0 = 0.272 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT1 = 0.241 ns
-- For block PLL_ADV_INST, Estimated PLL Jitter for CLKOUT2 = 0.212 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity PLL_CLOCK is
   port ( CLKIN1_IN    : in    std_logic; 
          CLKFBOUT_OUT : out   std_logic; 
          CLKOUT0_OUT  : out   std_logic; 
          CLKOUT1_OUT  : out   std_logic; 
          CLKOUT2_OUT  : out   std_logic);
end PLL_CLOCK;

architecture BEHAVIORAL of PLL_CLOCK is
   signal CLKFBIN_IN   : std_logic;
   signal CLKFBOUT_BUF : std_logic;
   signal CLKIN1_IBUFG : std_logic;
   signal CLKOUT0_BUF  : std_logic;
   signal CLKOUT1_BUF  : std_logic;
   signal CLKOUT2_BUF  : std_logic;
   signal GND_BIT      : std_logic;
   signal GND_BUS_5    : std_logic_vector (4 downto 0);
   signal GND_BUS_16   : std_logic_vector (15 downto 0);
   signal VCC_BIT      : std_logic;
begin
   GND_BIT <= '0';
   GND_BUS_5(4 downto 0) <= "00000";
   GND_BUS_16(15 downto 0) <= "0000000000000000";
   VCC_BIT <= '1';
   CLKFBOUT_OUT <= CLKFBIN_IN;
   CLKFBOUT_BUFG_INST : BUFG
      port map (I=>CLKFBOUT_BUF,
                O=>CLKFBIN_IN);
   
   CLKIN1_IBUFG_INST : IBUFG
      port map (I=>CLKIN1_IN,
                O=>CLKIN1_IBUFG);
   
   CLKOUT0_BUFG_INST : BUFG
      port map (I=>CLKOUT0_BUF,
                O=>CLKOUT0_OUT);
   
   CLKOUT1_BUFG_INST : BUFG
      port map (I=>CLKOUT1_BUF,
                O=>CLKOUT1_OUT);
   
   CLKOUT2_BUFG_INST : BUFG
      port map (I=>CLKOUT2_BUF,
                O=>CLKOUT2_OUT);
   
   PLL_ADV_INST : PLL_ADV
   generic map( BANDWIDTH => "OPTIMIZED",
            CLKIN1_PERIOD => 32.552,
            CLKIN2_PERIOD => 10.000,
            CLKOUT0_DIVIDE => 20,
            CLKOUT1_DIVIDE => 10,
            CLKOUT2_DIVIDE => 5,
            CLKOUT0_PHASE => 0.000,
            CLKOUT1_PHASE => 0.000,
            CLKOUT2_PHASE => 0.000,
            CLKOUT0_DUTY_CYCLE => 0.500,
            CLKOUT1_DUTY_CYCLE => 0.500,
            CLKOUT2_DUTY_CYCLE => 0.500,
            COMPENSATION => "SYSTEM_SYNCHRONOUS",
            DIVCLK_DIVIDE => 1,
            CLKFBOUT_MULT => 20,
            CLKFBOUT_PHASE => 0.0,
            REF_JITTER => 0.000000)
      port map (CLKFBIN=>CLKFBIN_IN,
                CLKINSEL=>VCC_BIT,
                CLKIN1=>CLKIN1_IBUFG,
                CLKIN2=>GND_BIT,
                DADDR(4 downto 0)=>GND_BUS_5(4 downto 0),
                DCLK=>GND_BIT,
                DEN=>GND_BIT,
                DI(15 downto 0)=>GND_BUS_16(15 downto 0),
                DWE=>GND_BIT,
                REL=>GND_BIT,
                RST=>GND_BIT,
                CLKFBDCM=>open,
                CLKFBOUT=>CLKFBOUT_BUF,
                CLKOUTDCM0=>open,
                CLKOUTDCM1=>open,
                CLKOUTDCM2=>open,
                CLKOUTDCM3=>open,
                CLKOUTDCM4=>open,
                CLKOUTDCM5=>open,
                CLKOUT0=>CLKOUT0_BUF,
                CLKOUT1=>CLKOUT1_BUF,
                CLKOUT2=>CLKOUT2_BUF,
                CLKOUT3=>open,
                CLKOUT4=>open,
                CLKOUT5=>open,
                DO=>open,
                DRDY=>open,
                LOCKED=>open);
   
end BEHAVIORAL;


