######################################################################
##
## Filename: PLL_CLOCK.udo
## Created on: Thu Dec 28 4:25:56 AM Eastern Standard Time 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
