-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\DSM_MOD8_HDL\Sign.vhd
-- Created: 2018-01-08 05:56:34
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Sign
-- Source Path: DSM_MOD8_HDL/Eight_order_delta_sigma_modulator/Sign
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Sign IS
  PORT( u                                 :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En32
        y                                 :   OUT   std_logic_vector(1 DOWNTO 0)  -- sfix2
        );
END Sign;


ARCHITECTURE rtl OF Sign IS

  -- Signals
  SIGNAL u_signed                         : signed(35 DOWNTO 0);  -- sfix36_En32
  SIGNAL y_tmp                            : signed(1 DOWNTO 0);  -- sfix2

BEGIN
  u_signed <= signed(u);

  
  y_tmp <= to_signed(-16#1#, 2) WHEN u_signed < to_signed(0, 36) ELSE
      to_signed(16#1#, 2);

  y <= std_logic_vector(y_tmp);

END rtl;

